name: Test R dependency installation

on:
  push:
    branches:
      - r-dependency-install-fix

jobs:
  upload:
    name: R dependency install test
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: Checkout data repo
        uses: actions/checkout@v2
        with:
          repository: epidemics/epimodel-covid-data
          path: data-pipeline/data

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.0.2'

      - name: Install os R dependencies
        run: sudo apt install libcurl4-openssl-dev libxml2-dev libssl-dev

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/dependencies.R') }}

      - name: Install R dependencies
        working-directory: data-pipeline
        run: Rscript ./scripts/dependencies.R